// Autogenerated AST node on 08/11/2020, 15:59:03
package astnodes.ast;

import astnodes.AST;

public enum expr_contextType {
    UNDEFINED,
    Load,
    Store,
    Del,
    AugLoad,
    AugStore,
    Param;
}
